name = "pre_stics"
version = "0.1.0"
license = "license"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"

[dependencies]
stdlib.git = "https://github.com/fortran-lang/stdlib"
stdlib.branch = "stdlib-fpm"
